mgr_url: "192.168.0.31:7180"
mgr_user: "admin"
mgr_pwd: "admin"

cluster_name: "Cluster%201"
hbase_user: "hbase"
hbase_group: "hbase"
hdfs_user: "hdfs"
hbase_lib_path: "/usr/lib/hbase/lib"
hbase_xml_file: "/etc/hbase/conf/hbase-site.xml"

java_home: "/usr/java/jdk1.7.0_67-cloudera"
ldap_security: "n"
dcs_count: "16"
my_nodes: "-w eason-1 -w eason-2"
node_list: " eason-1 eason-2"
first_node: "eason-1"
rpm_basename: "trafodion"
traf_start: "y"
traf_rpm: "/home/centos/trafodion-2.0.0-1.x86_64.rpm" 
traf_pwd: "traf123"

