---
- hosts: 
  - trafnodes
  roles:
  - traf_check
  - traf_rpm
  - traf_setup

- hosts:
  - localhost
  roles:
  - hadoop_mods
  tags: mod

- hosts:
  - firstnode
  roles:
  - hdfs_cmds
  - traf_start

- hosts:
  - firstnode
  roles:
  - traf_security
  tags: ldap
