---
- hosts: 
  - localhost
  roles:
  - traf_vars
  tags: var_tag

- hosts: 
  - trafnodes
  roles:
  - traf_check
  - traf_rpm
  - traf_setup
  tags: install_tag


- hosts:
  - firstnode
  roles:
  - hadoop_mods
  - traf_start
  tags: install_tag

