---
#- hosts: 
#  - localhost
#  roles:
#  - traf_vars
#  tags: var_tag

- hosts: 
  - trafnodes
  roles:
  - traf_check
  - traf_rpm
  - traf_setup


- hosts:
  - localhost
  roles:
  - hadoop_mods

- hosts:
  - firstnode
  roles:
  - hdfs_cmds
  - traf_start
