---
- hosts: 
  - trafnodes
  roles:
  - traf_check
  - traf_rpm
  - traf_setup
  tags: setup

- hosts: 
  - trafnodes
  roles:
  - dbmgr_setup
  tags: dbmgr

- hosts:
  - trafnodes
  roles:
  - hadoop_mods
  tags: apache_mod

- hosts:
  - localhost
  roles:
  - hadoop_mods
  tags: mod

- hosts:
  - firstrsnode
  roles:
  - hdfs_cmds
  tags: hdfs

- hosts:
  - firstnode
  roles:
  - traf_security
  tags: ldap

- hosts:
  - firstnode
  roles:
  - traf_start
  tags: start
