---
- hosts: 
  - localhost
  roles:
  - traf_vars

- hosts: 
  - trafnodes
  roles:
  - traf_check
  - traf_rpm
  - traf_setup


- hosts:
  - firstnode
  roles:
  - hadoop_mods
  - traf_start

- hosts: 
  - trafnodes
  roles:
  - { role: traf_ha when: traf_enable_ha=='y' }
