---
# TODO: remove related system configs
- name: Check trafodion home existence
  stat: path=/home/trafodion/
  register: trafuser
  
- name: Stop trafodion processes if exist
  shell: "source /home/trafodion/.bashrc; echo 'y'|ckillall; sleep 5"
  sudo: yes
  sudo_user: trafodion
  ignore_errors: true
  when: trafuser.stat.exists==True

- name: Uninstall trafodion RPM
  yum: name=trafodion state=absent
  sudo: yes

- name: Remove trafodion RPM and user home directory
  shell: "rm /home/trafodion /tmp/trafodion*.rpm -rf"
  sudo: yes

- name: Delete trafodion user
  user: name=trafodion state=absent remove=yes
  sudo: yes

