---
# TODO: remove related system configs
- name: Check trafodion home existence
  stat: path=/home/trafodion/
  register: trafuser
  
- name: Stop trafodion processes if exist
  shell: "source /home/trafodion/.bashrc; echo 'y'|ckillall; sleep 5"
  become: yes
  become_user: trafodion
  ignore_errors: true
  when: inventory_hostname in groups['firstnode'] and trafuser.stat.exists==True

- name: Uninstall trafodion RPM
  yum: name=trafodion state=absent
  become: yes

- name: Remove trafodion RPM and user home directory
  shell: "rm /home/trafodion /tmp/trafodion*.rpm -rf"
  become: yes

- name: Kill all trafodion user processes
  shell: "ps -ef|grep trafodion|grep -v grep |awk '{print $2}'|xargs kill -9; echo -n"
  become: yes
  become_user: trafodion
  ignore_errors: true

- name: Delete trafodion user
  user: name=trafodion state=absent remove=yes
  become: yes

