---
- name: parse manager url password
  shell: "echo {{ mgr_pwd }} | base64 -d"
  register: pwd

# use a different var name since config var mgr_pwd 
# will overwrite the value set here
- set_fact:
    mgrpwd: "{{ pwd.stdout }}"

- include: modify_cdh.yml
  when: "'CDH' in distro"
- include: restart_cdh.yml
  when: "'CDH' in distro"

- include: modify_hdp.yml
  when: "'HDP' in distro"
- include: restart_hdp.yml
  when: "'HDP' in distro"
