---
- name: Install Cloudera Manager on master node
  yum: name=cloudera-manager-server,cloudera-manager-server-db-2,cloudera-manager-daemons,cloudera-manager-agent state=present
  become: yes
  when: inventory_hostname in groups['cdhmaster']

- name: Install Cloudera agent on all nodes
  yum: name=cloudera-manager-daemons,cloudera-manager-agent state=present
  become: yes

- name: Install JDK1.7 on all nodes
  yum: name=oracle-j2sdk1.7 state=present
  become: yes

- set_fact:
    parcel_dir: '/opt/home/parcel/5.4.8-rhel/'

- name: Copy Parcel files to Cloudera Manager node
  copy: src={{ parcel_dir }}/ dest=/opt/cloudera/parcel-repo/ directory_mode=yes
  become: yes
  when: inventory_hostname in groups['cdhmaster']

- name: Start Cloudera server DB
  service: name=cloudera-scm-server-db state=restarted
  become: yes
  when: inventory_hostname in groups['cdhmaster']

- name: Start Cloudera server
  service: name=cloudera-scm-server state=restarted
  become: yes
  when: inventory_hostname in groups['cdhmaster']

- name: Modify Cloudera agent settings
  replace: dest=/etc/cloudera-scm-agent/config.ini
           regexp='server_host=.*'
           replace="server_host={{ groups['cdhmaster'][0] }}"

- name: Start Cloudera agent
  service: name=cloudera-scm-agent state=restarted
  become: yes
