---
# run on firstnode
- name: Get SQROOT var
  shell: "rpm -ql {{ rpm_basename }} |head -1"
  register: sq_root
    
- name: Generate LDAP config file
  template: src=traf_authentication_conf.j2 dest={{ sq_root.stdout }}/sql/scripts/traf_authentication_config
  sudo_user: trafodion
  sudo: yes

- name: Check LDAP config file using ldapconfigcheck
  shell: "source /home/trafodion/.bashrc; ldapconfigcheck -file {{ sq_root.stdout }}/sql/scripts/traf_authentication_config"
  sudo_user: trafodion
  sudo: yes

- name: Enable LDAP security using traf_authentication_setup
  shell: "source /home/trafodion/.bashrc; cd $MY_SQROOT/sql/scripts; traf_authentication_setup --setup --file traf_authentication_config"
  sudo_user: trafodion
  sudo: yes
