#!/bin/bash

hdfs dfs -mkdir /hbase-staging 2>/dev/null
hdfs dfs -chown -R hbase:hbase /hbase-staging

hdfs dfs -mkdir /bulkload 2>/dev/null
hdfs dfs -chown -R trafodion:trafodion /bulkload

hdfs dfs -mkdir /lobs 2>/dev/null
hdfs dfs -chown -R trafodion:trafodion /lobs

hdfs dfs -mkdir -p /hbase/archive 2>/dev/null
hdfs dfs -chown hbase:hbase /hbase/archive

