#!/bin/bash

core=$1
proc=$2
sqconfig=$3
scratch_locs=$4
nodes=$5

node_id=0
echo "begin node" > $sqconfig
for node in $nodes; do
    echo "node-id=$node_id;node-name=$node;cores=0-$core;processors=$proc;roles=connection,aggregation,storage" >> $sqconfig
    ((node_id++))
done
echo "end node" >> $sqconfig

echo >> $sqconfig

echo "begin overflow" >> $sqconfig
for loc in $scratch_locs; do
    echo "hdd $loc" >> $sqconfig
done
echo "end overflow" >> $sqconfig
